### ISSUE TITLE
Fail to load archieve, edit-reader not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', ....

### ISSUE THREAD

**Issue by romasigo** [isomap/factedit#1]
Hello, I'm trying to run the model with  pretrained checkpoint the development set of WebEdit data on Google Colab.
`!python predict.py ./data/webedit/dev.jsonl \
                  ./models/webedit.tar.gz \
                  --cuda_device -1`

But I get error bellow. Is there any solution to solve this issue?
#Traceback (most recent call last):
  File "predict.py", line 38, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "predict.py", line 20, in main
    model, config = load_archive(archive_file=archive_file, cuda_device=cuda_device)
  File "/usr/local/lib/python3.7/dist-packages/allennlp/models/archival.py", line 233, in load_archive
    config.duplicate(), serialization_dir
  File "/usr/local/lib/python3.7/dist-packages/allennlp/models/archival.py", line 269, in _load_dataset_readers
    dataset_reader_params, serialization_dir=serialization_dir
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/from_params.py", line 588, in from_params
    default_to_first_choice=default_to_first_choice,
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/params.py", line 324, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: edit-reader not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', 'multitask', 'multitask_shim', 'sequence_tagging', 'sharded', 'text_classification_json', 'masked_language_modeling', 'next_token_lm', 'simple_language_modeling', 'copynet_seq2seq', 'seq2seq', 'cnn_dm']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.

**Comment by isomap** [comment]
Hi @romasigo 

Thanks for your interest :)
I tried to run it again locally in my newly created environment and it works with fixing some minor issues.
(e.g., update overrides version to solve the following issue: https://github.com/allenai/specter/issues/27#issuecomment-866667471 ) 

I've never used colab so I cannot figure out why that issue happened...
But I guess if you execute the following line, you would not face that issue... https://github.com/isomap/factedit/blob/main/predict.py#L10

Please check this and your allennlp's version again, and please let me know if you need further help.

Thanks!

**Comment by romasigo** [comment]
Thank for your reply @isomap. I had updated overrides version before.

My bad, I forgot to make sure which allennlp version is running in my colab. So I reinstalled allennlp `!pip install allennlp==0.9.0` outside of requirement.txt.

And now I face new issue. I think it is related with allennlp.models. What is the version of your allennlp_models? Seems there is no version 0.9.0 for allennlp_models.
`ERROR: Could not find a version that satisfies the requirement allennlp_models==0.9.0 (from versions: 1.0.0rc1, 1.0.0rc2,..)`

Here is my error:
File "predict.py", line 11, in <module>
    from util import batch, Evaluator
  File "factedit/util.py", line 7, in <module>
    from allennlp_models.generation.predictors.seq2seq import Seq2SeqPredictor
  File "/usr/local/lib/python3.7/dist-packages/allennlp_models/generation/__init__.py", line 2, in <module>
    from allennlp_models.generation.modules import *
  File "/usr/local/lib/python3.7/dist-packages/allennlp_models/generation/modules/__init__.py", line 2, in <module>
    from allennlp_models.generation.modules.decoder_nets import *
  File "/usr/local/lib/python3.7/dist-packages/allennlp_models/generation/modules/decoder_nets/__init__.py", line 3, in <module>
    from allennlp_models.generation.modules.decoder_nets.stacked_self_attention import (
  File "/usr/local/lib/python3.7/dist-packages/allennlp_models/generation/modules/decoder_nets/stacked_self_attention.py", line 14, in <module>
    from allennlp_models.lm.modules.seq2seq_encoders.bidirectional_lm_transformer import (
  File "/usr/local/lib/python3.7/dist-packages/allennlp_models/lm/__init__.py", line 2, in <module>
    from allennlp_models.lm.dataset_readers import *
  File "/usr/local/lib/python3.7/dist-packages/allennlp_models/lm/dataset_readers/__init__.py", line 1, in <module>
    from allennlp_models.lm.dataset_readers.masked_language_model import MaskedLanguageModelingReader
  File "/usr/local/lib/python3.7/dist-packages/allennlp_models/lm/dataset_readers/masked_language_model.py", line 9, in <module>
    from allennlp.data.tokenizers.whitespace_tokenizer import WhitespaceTokenizer
ModuleNotFoundError: No module named 'allennlp.data.tokenizers.whitespace_tokenizer'

**Comment by isomap** [comment]
I think your code is not exactly same with the code on Github, e.g., https://github.com/isomap/factedit/blob/main/util.py#L6
Your error message says:
```
File "factedit/util.py", line 7, in
from allennlp_models.generation.predictors.seq2seq import Seq2SeqPredictor
```
but I don't use `allennlp_models` here, so I have no idea for the problem.

So, please consider to create new environment from scratch and clone the clean repo again to check.
Again, I had no issue when I create the new environment. 

Thank you!

**Comment by romasigo** [comment]
Thank you for your suggestion @isomap . Now I can run the pretrained model by creating new environment and some addition set-up on google colab. 

In the end of prediction using WEBEDIT model, I got this score and it is a little different from what you presented on your [paper ](https://aclanthology.org/2020.acl-main.17/). I didn't make any changes to either the data and code. Could you explain why is this happen? 
`{'BLEU': 0.7729257356235401, 'EM': 0.2535853690627604, 'SARI': 0.7625368100101709, 'KEEP': 0.9366403899290523, 'ADD': 0.52675551794372, 'DEL': 0.8242145221577428}`

And also I didn't see printed Fidelity score (P%, R%, F1%) and Runtime analysis score. How do we print these score?

**Comment by isomap** [comment]
The results of the paper are about the test set. What you did is on the dev set.

Other scores should be implemented by yourself.

Thanks

**Comment by romasigo** [comment]
I appreciate your suggestion @isomap.
I'm rerunning now. 
Could you please help me how to implement other score? To be honest, I haven't any idea to start based on what I read on your [paper](https://aclanthology.org/2020.acl-main.17/) page 177. :) 

Thanks.

**Comment by isomap** [comment]
For WebEdit, you can extract the list of entities from the dataset and evaluate their performance based on string matching.
For RotoEdit, please check this: https://github.com/harvardnlp/data2text

**Comment by romasigo** [comment]
@isomap  I'll try. Thanks for your help.
